services:
  app:
    build: .
    platform: linux/arm64
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_IPFS_API_URL=http://ipfs:5001
      - NEXT_PUBLIC_IPFS_GATEWAY=http://localhost:8080/ipfs
      - OLLAMA_API_URL=http://ollama:11434
      - RISC0_DEV_MODE=1
    depends_on:
      - ipfs
      - ollama
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 12g

  ollama:
    image: ollama/ollama:latest
    platform: linux/arm64
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ipfs:
    image: ipfs/kubo:latest
    platform: linux/arm64
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      - IPFS_PROFILE=server

volumes:
  ollama_data:
  ipfs_data: