services:
  app:
    build: .
    platform: linux/arm64
    ports:
      - "3000:3000"
    # Load developer secrets (not committed) from local file.
    # Create a copy of .env.example named .env.local before running.
    env_file:
      - .env.local
    environment:
      - NEXT_PUBLIC_IPFS_API_URL=http://ipfs:5001
      - NEXT_PUBLIC_IPFS_GATEWAY=http://localhost:8080/ipfs
      # Add internal gateway for server-side verification (app container cannot use localhost:8080 for IPFS)
      - IPFS_GATEWAYS=http://ipfs:8080/ipfs,https://ipfs.io/ipfs,https://cloudflare-ipfs.com/ipfs
      - OLLAMA_API_URL=http://ollama:11434
      - RISC0_DEV_MODE=1
    depends_on:
      - ipfs
      - ollama
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 12g

  ollama:
    image: ollama/ollama:latest
    platform: linux/arm64
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ipfs:
    image: ipfs/kubo:latest
    platform: linux/arm64
    ports:
      - "4001:4001" # IPFS swarm port
      - "5001:5001" # IPFS API port
      - "8080:8080" # IPFS gateway port
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      - IPFS_PROFILE=server

volumes:
  ollama_data:
  ipfs_data:

networks:
  ai-proof-network:
    driver: bridge
